import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./splide.css";
import { Header } from "./components/layout/Header";
import { Footer } from "./components/layout/Footer";
import { ReactQueryProvider } from "./ReactQueryProvider";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <div className="container">
            <Header
              items={[
                { title: "Bosh sahifa", link: "/" },
                { title: "Biz haqimizda", link: "/about" },
                { title: "Mahsulotlar", link: "/products" },
                { title: "Aloqa", link: "/contacts" },
              ]}
              // phone="+1234567890"
            />
          </div>
     
          {children}
       
          <div className="container">
            <Footer 
              itemssahifa={[
                {title: "Bosh sahifa", link: "/"},
                {title: "Biz haqimizda", link: "/about"},
                {title: "Mahsulotlar", link: "/products"},
                {title: "Aloqa", link: "/contacts"},
              ]}
              itemsaloqa = {[
                {title: "Yakkabog' ko'chasi, 54, Chilonzor tumani, Toshkent", link: "#!", img: "/location.svg"},
                {title: "+998 XX XXX XX XX", link: "tel:+1234567890", img: "/phone.svg"},
                {title: "example@gmail.com", link: "mailto:mail@mail.ru", img: "/mail.svg"},
              ]}
              itemsishvaqti = {[
                {days: "Dushanba - Juma", hourfrom: "9:00 dan", hourto: "19:00 gacha"},
                {days: "Shanba", hourfrom: "9:00 dan", hourto: "19:00 gacha"},
                {days: "Yakshanba", hourfrom: "9:00 dan", hourto: "19:00 gacha"},
              ]}
              itemssocial = {[
                {platform: "Facebook", link: "https://facebook.com", icon: "/facebook.svg"},
                {platform: "Twitter", link: "https://twitter.com", icon: "/twitter.svg"},
                {platform: "Instagram", link: "https://instagram.com", icon: "/instagram.svg"},
                {platform: "YouTube", link: "https://youtube.com", icon: "/youtube.svg"},
              ]}
              description="Har bir mahsulotimiz — nafis dizayn, ishonchli material va puxta ishlovning ifodasi. Uy, ofis yoki jamoat joylari uchun mo‘ljallangan mebellarimiz hayotingizga iliqlik va qulaylik baxsh etadi."
              copyright = "© 2025 VIA All rights reserved. | Privacy Policy | Terms of Service"
            />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
